version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.22.0
    - 5.24.0
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.14
